apiVersion: synthetics.heimdall.dev/v1alpha1
kind: Platform
metadata:
  name: heimdall
spec:
  defaults:
    timeout: 5m
    values: {}
  maxConcurrentRuns: 100
  maxSteps: 1000
  maxResponseBytes: 1048576
